global:
  environment: production

backend:
  replicas: 1
  image:
    repository: indeicheg/sausage-backend
    tag: latest
    pullPolicy: Always
  service:
    port: 8080
  database:
    url: jdbc:postgresql://postgresql:5432/sausage-store
    username: store
    password: storepassword
  mongodb:
    uri: mongodb://root:rootpassword@mongodb:27017/sausage-store?authSource=admin
  vault:
    enabled: "false"
  resources:
    requests:
      cpu: 250m
      memory: 300Mi
    limits:
      cpu: 700m
      memory: 600Mi
  livenessProbe:
    path: /actuator/health
    initialDelaySeconds: 60
    periodSeconds: 15
  vpa:
    enabled: true
    updateMode: "Off"

backend-report:
  replicas: 1
  image:
    repository: indeicheg/sausage-backend-report
    tag: latest
    pullPolicy: Always
  service:
    port: 8080
  env:
    port: "8080"
    db: mongodb://root:rootpassword@mongodb:27017/sausage-store?authSource=admin
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 300m
      memory: 256Mi
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 75

frontend:
  replicas: 1
  image:
    repository: indeicheg/sausage-frontend
    tag: latest
    pullPolicy: Always
  service:
    port: 80
  ingress:
    enabled: true
    className: nginx
    host: front-dalukyanov.2sem.students-projects.ru
    tlsSecret: 2sem-students-projects-wildcard-secret
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

infra:
  postgresql:
    image: postgres:16-alpine
    database: sausage-store
    username: store
    password: storepassword
    storage: 1Gi
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  mongodb:
    image: mongo:7
    rootUsername: root
    rootPassword: rootpassword
    database: sausage-store
    storage: 1Gi
    resources:
      requests:
        cpu: 150m
        memory: 200Mi
      limits:
        cpu: 500m
        memory: 512Mi
