apiVersion: v1
kind: Secret
metadata:
  name: sausage-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "{{ .Values.database.url }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.database.username }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.database.password }}"
  SPRING_DATA_MONGODB_URI: "{{ .Values.mongodb.uri }}"
  SPRING_CLOUD_VAULT_ENABLED: "{{ .Values.vault.enabled }}"
  MANAGEMENT_HEALTH_VAULT_ENABLED: "false"
